spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fitwf
    username: fitwf_admin
    password: fitwf_pass

  jpa:
    show-sql: true
    generate-ddl: true
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_schema: fitwf
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

  mail:
    host: smtp.yandex.ru
    port: 465
    username: dsfsaegf@yandex.ru
    password: juxducmchucpbfsc
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true

jwt:
  token:
    secret: secret

