version: '3.1'

services:
  postgres:
    container_name: db_wf
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=fitwf_admin
      - POSTGRES_PASSWORD=fitwf_pass
      - POSTGRES_DB=fitwf
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

