<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
    <title>Title</title>
</head>
<body style="margin: 0; padding: 0">
<table border="0" cellspacing="0" cellpadding="0" width="100%">
    <tbody>
    <tr>
        <td align="center">
            <table style="border-collapse: collapse; font: 16px Verdana, serif; color: #FAFAFA; max-width:600px;"
                   width="100%" border="0"
                   cellpadding="0" cellspacing="0">
                <tbody style="background: #3F4954">
                <tr>
                    <td style="padding: 5px">
                        <strong style="padding:10px; font: bold 32px Tahoma">FIT<strong
                                    style="color: #D46B54">WF</strong></strong>
                    </td>
                </tr>
                </tbody>
                <tbody style="background: #2A323B">
                <tr>
                    <td>
                        <table style="margin: 0; padding: 40px; text-align: center" width="100%" border="0"
                               cellpadding="0"
                               cellspacing="0">
                            <tbody>
                            <tr>
                                <td style="background-color:#3F4954; padding: 30px; border: 2px solid #2A323B; border-radius: 15px">
                                    <strong style="font-size: 20px">Thank you for registering!</strong>
                                </td>
                            </tr>
                            <tr>
                                <td style="background-color:#3F4954; padding: 30px; border: 2px solid #2A323B; border-radius: 15px 15px 0 0; border-bottom-style: none">
                                    <span>Hi, ${username}!</span>
                                    <br>
                                    <br>
                                    <span>We have successfully processed your registration request.</span>
                                    <br>
                                    <span>It remains only to confirm the email:</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="background-color:#3F4954; padding: 0 0 45px 0; border: 2px solid #2A323B;  border-radius: 0 0 15px 15px; border-top-style: none">

                                    <a href="${buttonLink}" target="_blank"
                                       style="text-decoration: none; background: #928FEF; padding: 15px; font: 18px Verdana; color: #1c2128; border-radius: 5px">
                                        <strong>Confirm email</strong>
                                    </a>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
</body>
</html>